### ISSUE TITLE
Aucune commande dans Traccar

### ISSUE THREAD

**Issue by kenn5108** [dough29/Jeedom-Traccar#4]
Bonjour,

Dans le plugin Traccar pour Jeedom, il n'y a pas de commandes permettant de récupérer l'ignition et le mouvement du véhicule.
Y a t'il une opération manuelle à effectuer pour que cela fonctionne ?
J'ai bien paramétré le XML dans Traccar.

**Comment by dough29** [comment]
Bonjour,

ces commandes se créent automatiquement dès lors que le serveur Traccar les reçois et les transfert à Jeedom.

Si elles semblent ne pas se créer passer les logs en mode debug et constater si les trames "event" sont bien reçues par Jeedom.

Si les trames "event" ne passent pas vérifier la bonne configuration de Traccar pour la transmission vers Jeedom.

**Comment by kenn5108** [comment]
Bonjour,
Effectivement après avoir roulé un peu avec le véhicule, les commandes se sont créées.
Merci :)
